name: mng_ui
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0
  cupertino_icons: ^1.0.8
  http: ^0.13.5
  image_picker: ^1.0.7 
  # shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  web_socket_channel: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/download.jpeg
